parameters:
    r: "bundles/forsetiadmin/"
    r.img: "bundles/forsetiadmin/img/"
    startingPage: Article
    site_icon: '/img/admin_logo.png'

imports:
    - { resource: admin/group.yml }
    - { resource: admin/user.yml }
    
easy_admin:
    site_name: "<b>Abstract worlds</b> Admin"
    list:
        actions:
            - { name: 'show', icon: 'search' }
            - { name: 'edit', icon: 'pencil' }
            - { name: 'delete', icon: 'trash' }
    show:
        actions:
            - { name: 'edit', icon: 'pencil' }
            - { name: 'delete', icon: 'trash' }
    edit:
        actions:
            - { name: 'delete', icon: 'trash', label: '' }
    design:
        theme: default
        color_scheme: dark
        brand_color: '#0A7840'
        assets:
            css: ['%r%css/custom.css', '%r%colorpicker/bootstrap-colorpicker.min.css', '%r%datetimepicker/bootstrap-datetimepicker.min.css', '%r%selectivity/selectivity-full.min.css', '%r%tagsinput/bootstrap-tagsinput.css', '%r%spinner/touchspin.min.css']
            js: ['%r%colorpicker/bootstrap-colorpicker.min.js', '%r%selectivity/selectivity-full.min.js', '%r%datetimepicker/moment-with-locales.min.js', '%r%datetimepicker/bootstrap-datetimepicker.min.js', '%r%tagsinput/bootstrap-tagsinput.min.js', '%r%spinner/touchspin.min.js']
        menu: 
            - 
              label: easyAdmin.menu.div.pages 
            - { entity: 'Article', icon: 'file-text-o', label: easyAdmin.article.name.mm, default: true }
            - { entity: 'Attachment', icon: 'paperclip', label: easyAdmin.attachment.name.mm }
            - { entity: 'Image', icon: 'picture-o', label: easyAdmin.image.name.mm }
            - { entity: 'Comment', icon: 'comments-o', label: easyAdmin.comment.name.mm }
            - { entity: 'Category', icon: 'folder', label: easyAdmin.category.name.mm }
            - { entity: 'Tag', icon: 'tags', label: easyAdmin.tag.name.mm }
            - 
              label: easyAdmin.menu.div.dicts
            - { entity: 'Filetype', icon: 'file-code-o', label: easyAdmin.filetype.name.mm }
            - { entity: 'Licence', icon: 'certificate', label: easyAdmin.licence.name.mm }
            - 
              label: easyAdmin.menu.div.users
            - { entity: 'User', icon: 'user', label: easyAdmin.user.name.mm }
            - { entity: 'Group', icon: 'group', label: easyAdmin.group.name.mm }
        form_theme: '@ForsetiAdmin/form/bootstrap_3_layout.html.twig'
        templates:
            layout: '@ForsetiAdmin/easy_admin/layout.html.twig'
            menu: '@ForsetiAdmin/easy_admin/menu.html.twig'
            show: '@ForsetiAdmin/easy_admin/show.html.twig' 

