parameters:
    a.css: "bundles/forsetiadmin/css/"
    a.img: "bundles/forsetiadmin/img/"
    a.js: "bundles/forsetiadmin/js/"
    startingPage: Article
    site_icon: '/img/admin_logo.png'

imports:
    - { resource: admin/group.yml }
    - { resource: admin/user.yml }
    
easy_admin:
    site_name: "<b>Abstract worlds</b> Admin"
    list:
        actions:
            - { name: 'show', icon: 'search' }
            - { name: 'edit', icon: 'pencil' }
            - { name: 'delete', icon: 'trash' }
    show:
        actions:
            - { name: 'edit', icon: 'pencil' }
            - { name: 'delete', icon: 'trash' }
    edit:
        actions:
            - { name: 'delete', icon: 'trash', label: '' }
    design:
        theme: default
        color_scheme: dark
        brand_color: '#0A7840'
        assets:
            css: ['%a.css%custom.css', '%a.css%bootstrap-colorpicker.min.css', '%a.css%sol.css', '%a.css%bootstrap-datetimepicker.min.css']
            js: ['%a.js%bootstrap-colorpicker.min.js', '%a.js%sol.js', '%a.js%moment-with-locales.min.js', '%a.js%bootstrap-datetimepicker.min.js']
        form_theme: '@ForsetiAdmin/form/bootstrap_3_layout.html.twig'
        templates:
            layout: '@ForsetiAdmin/easy_admin/layout.html.twig'
            menu: '@ForsetiAdmin/easy_admin/menu.html.twig'
            show: '@ForsetiAdmin/easy_admin/show.html.twig' 

