imports:
    - { resource: admin.yml }
        
fos_user:
    db_driver: orm
    firewall_name:  main
    user_class:    Forseti\AdminBundle\Entity\User
    group:
        group_class:   Forseti\AdminBundle\Entity\Group
        
services:
    admin.getquery_voter:
        class:      Forseti\AdminBundle\Security\GetQueryAccessVoter
        arguments:  [ "@request_stack" , "@service_container" ]
        tags:       [ { name: 'security.voter' } ]
        public:     false
        