imports:
    - { resource: admin.yml }
        
fos_user:
    db_driver: orm
    firewall_name:  main
    user_class:    Forseti\AdminBundle\Entity\User
    group:
        group_class:   Forseti\AdminBundle\Entity\Group
        
ivory_ck_editor:
    input_sync: true
    default_config: all
    configs:
        all:
            toolbar:
        simple_config:
            toolbar:
                - { name: 'basicstyles', items: [ 'Bold', 'Italic', 'Underline', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] }
        advanced_config:
            toolbar:
                - { name: 'document', items: [ 'NewPage', 'Templates', 'Save', '-', 'Preview', 'Print' ] }
                - { name: 'clipboard', items: [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ] }
                - { name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] }
                - { name: 'insert', items: [ 'Blockquote', 'Image', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar' ] }
                - { name: 'editing', items: [ 'Find', 'Replace', 'Scayt' ] }
                - '/'
                - { name: 'styles', items: [ 'Styles', 'Format', 'Font', 'FontSize' ] }
                - { name: 'basicstyles', items: [ 'Bold', 'Italic', 'Underline', 'Subscript', 'Superscript', '-', 'TextColor', 'BgColor', '-', 'RemoveFormat' ] }
                - { name: 'extendedstyles', items: ['Color', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' ] }
                - { name: 'paragraph', items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent' ] }
