services:
    admin.getquery_voter:
        class:      Forseti\AdminBundle\Security\GetQueryAccessVoter
        arguments:  [ "@request_stack" , "@service_container", "entity", "action" ]
        tags:       [ { name: 'security.voter' } ]
        public:     false
