imports:
    - { resource: admin/article.yml }
    - { resource: admin/attachment.yml }
    - { resource: admin/filetype.yml }
    - { resource: admin/image.yml }
    - { resource: admin/licence.yml }
