admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

homepage:
    path:      /{_locale}
    defaults: 
        _locale: "pl"
        _controller: "AppBundle:Default:index"
    requirements:
        _locale: pl|en 
    
easy_admin_bundle:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /admin
    
# FOS User Bundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    