    
user_login:
    path:   /user/login
    defaults:  { _controller: 'ForsetiAdminBundle:Security:login' }
  
admin:
    resource: "@ForsetiAdminBundle/Resources/config/routing-admin.yml"
    prefix: /admin
    
user:
    resource: "@ForsetiAdminBundle/Resources/config/routing-user.yml"
    prefix: /user
    
forseti_pages:
    resource: "@ForsetiPagesBundle/Controller/"
    type:     annotation
    prefix:   /

homepage:
    path:      /{_locale}
    defaults: 
        _locale: "pl"
        _controller: "ForsetiPagesBundle:Page:index"
    requirements:
        _locale: pl|en 
