homepage:
    path:      /{_locale}
    defaults: 
        _locale: "pl"
        _controller: "AppBundle:Default:index"
    requirements:
        _locale: pl|en 
  
admin:
    resource: "@ForsetiAdminBundle/Resources/config/routing-admin.yml"
    prefix: /admin
    
user:
    resource: "@ForsetiAdminBundle/Resources/config/routing-user.yml"
    prefix: /user
