security:
    role_hierarchy:
        ROLE_ARTICLE_SHOW: ~
        ROLE_ARTICLE_LIST: ROLE_ARTICLE_SEARCH
        ROLE_ARTICLE_NEW: ~
        ROLE_ARTICLE_EDIT: ~
        ROLE_ARTICLE_SOFTDELETE: ~
        ROLE_ARTICLE_DELETE: ROLE_ARTICLE_SOFTDELETE
        ROLE_ARTICLE_FLAG: ~
        ROLE_ARTICLE_OWN: [ ROLE_ARTICLE_SEE, ROLE_ARTICLE_NEW ]
        ROLE_ARTICLE_SEE:
            - ROLE_ARTICLE_SHOW
            - ROLE_ARTICLE_LIST
            - ROLE_ARTICLE_FLAG
        ROLE_ARTICLE_ALL:
            - ROLE_ARTICLE_SEE
            - ROLE_ARTICLE_NEW
            - ROLE_ARTICLE_EDIT
            - ROLE_ARTICLE_DELETE

easy_admin:
    entities:
        Article:
            class: Forseti\PagesBundle\Entity\Article
            label: easyAdmin.article.name.mp
            form: 
                fields:
                    - { property: 'name', label: 'easyAdmin.pages.name', type: text, css_class: 'col-sm-2' }
                    - { property: 'title', label: 'easyAdmin.pages.title', type: text, css_class: 'col-sm-10' }
                    - { property: 'lead', label: 'easyAdmin.articles.lead', type: 'ckeditor', type_options: { config_name: 'advanced_config' } }
                    - { property: 'content', label: 'easyAdmin.articles.content', type: 'ckeditor' }
                    -
                      property: 'category'
                      label: 'easyAdmin.category.name.mp'
                      css_class: 'col-sm-6'
                      type: entity
                      type_options:
                          class: Forseti\PagesBundle\Entity\Category
                          multiple: false

#                    -
#                      property: 'tags'
#                      label: 'easyAdmin.tag.name.mm'
#                      css_class: 'col-sm-6'
#                      type: entity
#                      type_options:
#                          class: Forseti\PagesBundle\Entity\Tag
#                          multiple: true

                    -  
                      property: 'images'
                      label: 'easyAdmin.image.name.mm'
                      type: entity
                      type_options: 
                          class: Forseti\PagesBundle\Entity\Image
                          multiple: true
                         
                    - 
                      property: 'attachments'
                      label: 'easyAdmin.attachment.name.mm'
                      type: entity
                      type_options: 
                          class: 'Forseti\PagesBundle\Entity\Attachment'
                          multiple: true

                    -
                      property: 'author'
                      label: 'easyAdmin.pages.author'
                      type: entity
                      type_options:
                          class: 'Forseti\AdminBundle\Entity\User'
                          multiple: false

                    - { property: 'metaTitle', label: 'easyAdmin.pages.meta_title', type: text }
                    - { property: 'metaKeywords', label: 'easyAdmin.pages.meta_keywords', type: text }
                    - { property: 'metaDesc', label: 'easyAdmin.pages.meta_desc', type: 'ckeditor' }
                    - { property: 'pageOrder', label: 'easyAdmin.pages.page_order', type: integer, css_class: 'col-sm-2' }
                    - { property: 'template', label: 'easyAdmin.pages.template', type: text, css_class: 'col-sm-2' }
                    - { property: 'cssClass', label: 'easyAdmin.pages.css_class', type: text, css_class: 'col-sm-2' }
            new:
                title: easyAdmin.article.title.new
            edit:
                title: easyAdmin.article.title.edit    
            show:
                title: easyAdmin.article.name.mm
                fields: 
                    - { property: 'id', label: 'ID', css_class: 'col-sm-2' }
                    - { property: 'name', label: 'easyAdmin.pages.name', css_class: 'col-sm-2' }
                    - { property: 'title', label: 'easyAdmin.pages.title', css_class: 'col-sm-8' }
                    - { property: 'lead', label: 'easyAdmin.articles.lead', type: raw }
                    - { property: 'content', label: 'easyAdmin.articles.content', type: raw }
                    - { property: 'category', label: 'easyAdmin.category.name.mp', css_class: 'col-sm-6' }
#                    - { property: 'tags', label: 'easyAdmin.tag.name.mm', css_class: 'col-sm-6' }
                    - { property: 'images', label: 'easyAdmin.image.name.mm', css_class: 'col-sm-6' }
                    - { property: 'attachments', label: 'easyAdmin.attachment.name.mm', css_class: 'col-sm-6' }
                    - { property: 'comments', label: 'easyAdmin.comment.name.mm' }
                    - { property: 'author', label: 'easyAdmin.pages.author' }
                    - { property: 'metaTitle', label: 'easyAdmin.pages.meta_title' }
                    - { property: 'metaKeywords', label: 'easyAdmin.pages.meta_keywords' }
                    - { property: 'metaDesc', label: 'easyAdmin.pages.meta_desc', type: ckeditor }
                    - { property: 'pageOrder', label: 'easyAdmin.pages.page_order', css_class: 'col-sm-2' }
                    - { property: 'template', label: 'easyAdmin.pages.template', css_class: 'col-sm-2' }
                    - { property: 'cssClass', label: 'easyAdmin.pages.css_class', css_class: 'col-sm-2' }
                    - { property: 'createdAt', label: 'easyAdmin.pages.createdAt', css_class: 'col-sm-2' }
                    - { property: 'modifiedAt', label: 'easyAdmin.pages.modifiedAt', css_class: 'col-sm-2' }
                    - { property: 'deletedAt', label: 'easyAdmin.pages.deletedAt', css_class: 'col-sm-2' }
#                    -
#                      property: 'images'
#                      label: 'easyAdmin.image.name.mm'
#                      css_class: 'col-sm-6'
#                      template: '@ForsetiAdmin/easy_admin/field_subview.html.twig'
#                      subview:
#                          entity: Image
#                          template: '@ForsetiAdmin/easy_admin/field_subview_thumbs.html.twig'
#                          actions: [ new, filter, deleteAll, show, edit, delete ]
#                          fields: [ filename, title, size]
#                          order: pageOrder
                           
            list:
                title: easyAdmin.article.name.mm
                fields: 
                    - { property: 'id', label: 'ID' }
                    - { property: 'name', label: 'easyAdmin.pages.name', template: '@ForsetiAdmin/easy_admin/field_linked_string.html.twig' }
                    - { property: 'title', label: 'easyAdmin.pages.title' }
                    - { property: 'category', label: 'easyAdmin.category.name.mp' }
#                    - { property: 'tags', label: 'easyAdmin.tag.name.icon' }
                    - { property: 'images', label: 'easyAdmin.image.name.icon' }
                    - { property: 'attachments', label: 'easyAdmin.attachment.name.icon' }
                    - { property: 'comments', label: 'easyAdmin.comment.name.icon' }
                    - { property: 'author', label: 'easyAdmin.pages.author' }
                    - { property: 'isdeleted', label: 'easyAdmin.pages.deletedAt' }
                    - { property: 'pageOrder', label: 'easyAdmin.pages.page_order.icon' }
                    - { property: 'template', label: 'easyAdmin.pages.template' }
                    - { property: 'cssClass', label: 'easyAdmin.pages.css_class' }
                
                