security:
    role_hierarchy:
        ROLE_IMAGE_SHOW: ~
        ROLE_IMAGE_LIST: ~
        ROLE_IMAGE_NEW: ~
        ROLE_IMAGE_EDIT_OWN: ~
        ROLE_IMAGE_EDIT: ROLE_IMAGE_EDIT_OWN
        ROLE_IMAGE_SOFTDELETE_OWN: ~
        ROLE_IMAGE_SOFTDELETE: ROLE_IMAGE_SOFTDELETE_OWN
        ROLE_IMAGE_DELETE: ~
        ROLE_IMAGE_FLAG: ~
        ROLE_IMAGE_ALL:
            - ROLE_IMAGE_SHOW
            - ROLE_IMAGE_LIST
            - ROLE_IMAGE_NEW
            - ROLE_IMAGE_EDIT
            - ROLE_IMAGE_DELETE
            - ROLE_IMAGE_SOFTDELETE
            - ROLE_IMAGE_FLAG

easy_admin:
    entities:
        Image:
            class: Forseti\PagesBundle\Entity\Image
            label: easyAdmin.image.name.mp
            form: {}
            new:
                title: easyAdmin.image.title.new
            edit:
                title: easyAdmin.image.title.edit    
            show:
                title: easyAdmin.image.name.mp 
            list:
                title: easyAdmin.image.name.mm