security:
    role_hierarchy:
        ROLE_LICENCE_SHOW: ~
        ROLE_LICENCE_LIST: ~
        ROLE_LICENCE_NEW: ~
        ROLE_LICENCE_EDIT_OWN: ~
        ROLE_LICENCE_EDIT: ROLE_LICENCE_EDIT_OWN
        ROLE_LICENCE_SOFTDELETE_OWN: ~
        ROLE_LICENCE_SOFTDELETE: ROLE_LICENCE_SOFTDELETE_OWN
        ROLE_LICENCE_DELETE: ~
        ROLE_LICENCE_FLAG: ~
        ROLE_LICENCE_ALL:
            - ROLE_LICENCE_SHOW
            - ROLE_LICENCE_LIST
            - ROLE_LICENCE_NEW
            - ROLE_LICENCE_EDIT
            - ROLE_LICENCE_DELETE
            - ROLE_LICENCE_SOFTDELETE
            - ROLE_LICENCE_FLAG

easy_admin:
    entities:
        Licence:
            class: Forseti\PagesBundle\Entity\Licence
            label: easyAdmin.licence.name.mp
            form: {}
            new:
                title: easyAdmin.licence.title.new
            edit:
                title: easyAdmin.licence.title.edit    
            show:
                title: easyAdmin.licence.name.mp 
            list:
                title: easyAdmin.licence.name.mm    