security:
    role_hierarchy:
        ROLE_LICENCE_SHOW: ~
        ROLE_LICENCE_LIST: ROLE_LICENCE_SEARCH
        ROLE_LICENCE_NEW: ~
        ROLE_LICENCE_EDIT: ~
        ROLE_LICENCE_SOFTDELETE: ~
        ROLE_LICENCE_DELETE: ROLE_LICENCE_SOFTDELETE
        ROLE_LICENCE_SEE:
            - ROLE_LICENCE_SHOW
            - ROLE_LICENCE_LIST
        ROLE_LICENCE_ALL:
            - ROLE_LICENCE_SEE
            - ROLE_LICENCE_NEW
            - ROLE_LICENCE_EDIT
            - ROLE_LICENCE_DELETE

easy_admin:
    entities:
        Licence:
            class: Forseti\PagesBundle\Entity\Licence
            label: easyAdmin.licence.name.mp
            form:
                fields:
                    -
                      property: 'name'
                      label: 'easyAdmin.pages.name'
                    - { property: 'longname', label: 'easyAdmin.licences.name'}
                    - { property: 'url', label: 'easyAdmin.licences.url'}
            new:
                title: easyAdmin.licence.title.new
            edit:
                title: easyAdmin.licence.title.edit    
            show:
                title: easyAdmin.licence.name.mp
                fields:
                    - { property: 'id', label: 'ID' }
                    -
                      property: 'name'
                      label: 'easyAdmin.pages.name'
                    - { property: 'longname', label: 'easyAdmin.licences.name'}
                    - { property: 'url', label: 'easyAdmin.licences.url', type: url}
            list:
                title: easyAdmin.licence.name.mm
                fields:
                    - { property: 'id', label: 'ID' }
                    -
                      property: 'name'
                      label: 'easyAdmin.pages.name'
                      template: '@ForsetiAdmin/easy_admin/field_linked_string.html.twig'
                    - { property: 'longname', label: 'easyAdmin.licences.name'}
                    - { property: 'url', label: 'easyAdmin.licences.url', type: url}
