security:
    role_hierarchy:
        ROLE_TAG_SHOW: ~
        ROLE_TAG_LIST: ~
        ROLE_TAG_NEW: ~
        ROLE_TAG_EDIT: ~
        ROLE_TAG_SOFTDELETE: ~
        ROLE_TAG_DELETE: ~
        ROLE_TAG_SEE:
            - ROLE_TAG_SHOW
            - ROLE_TAG_LIST
        ROLE_TAG_ALL:
            - ROLE_TAG_SEE
            - ROLE_TAG_LIST
            - ROLE_TAG_NEW
            - ROLE_TAG_EDIT
            - ROLE_TAG_DELETE
            - ROLE_TAG_SOFTDELETE

easy_admin:
    entities:
        Tag:
            class: Forseti\PagesBundle\Entity\Tag
            label: easyAdmin.tag.name.mp
            form: {}
            new:
                title: easyAdmin.tag.title.new
            edit:
                title: easyAdmin.tag.title.edit
            show:
                title: easyAdmin.tag.name.mp
            list:
                title: easyAdmin.tag.name.mm