security:
    role_hierarchy:
        ROLE_TAG_SHOW: ~
        ROLE_TAG_LIST: ~
        ROLE_TAG_NEW: ~
        ROLE_TAG_EDIT_OWN: ~
        ROLE_TAG_EDIT: ROLE_TAG_EDIT_OWN
        ROLE_TAG_SOFTDELETE_OWN: ~
        ROLE_TAG_SOFTDELETE: ROLE_TAG_SOFTDELETE_OWN
        ROLE_TAG_DELETE: ~
        ROLE_TAG_FLAG: ~
        ROLE_TAG_ALL:
            - ROLE_TAG_SHOW
            - ROLE_TAG_LIST
            - ROLE_TAG_NEW
            - ROLE_TAG_EDIT
            - ROLE_TAG_DELETE
            - ROLE_TAG_SOFTDELETE
            - ROLE_TAG_FLAG

easy_admin:
    entities:
        Tag:
            class: Forseti\PagesBundle\Entity\Tag
            label: easyAdmin.tag.name.mp
            form: {}
            new:
                title: easyAdmin.tag.title.new
            edit:
                title: easyAdmin.tag.title.edit
            show:
                title: easyAdmin.tag.name.mp
            list:
                title: easyAdmin.tag.name.mm