security:
    role_hierarchy: 
        ROLE_GROUP_SHOW: ~
        ROLE_GROUP_LIST: ROLE_GROUP_SEARCH
        ROLE_GROUP_NEW: ~
        ROLE_GROUP_EDIT: ~
        ROLE_GROUP_DELETE: ~
        ROLE_GROUP_SEE: 
            - ROLE_GROUP_SHOW
            - ROLE_GROUP_LIST
        ROLE_GROUP_ALL:
            - ROLE_GROUP_SEE
            - ROLE_GROUP_LIST
            - ROLE_GROUP_NEW
            - ROLE_GROUP_EDIT
            - ROLE_GROUP_DELETE

easy_admin:
    entities:
        Group:
            class: Forseti\AdminBundle\Entity\Group
            controller: Forseti\AdminBundle\Controller\UserAdminController
            label: easyAdmin.group.name.mp
            form:
                fields:
                    - { property: 'name', label: 'easyAdmin.groups.name', type: text }
                    -
                      property: 'color'
                      label: 'trait.color'
                      css_class: col-sm-3
                      type: '\Forseti\AdminBundle\Form\Type\ColorType'
                    -
                      property: 'roles'
                      label: 'easyAdmin.groups.roles'
                      type: choice
                      type_options:
                          expanded: false
                          multiple: true
                    - 
                      property: 'users' 
                      label: 'admin.group.users'
                      css_class: col-sm-5
                      type: entity
                      type_options: 
                          class: Forseti\AdminBundle\Entity\User
                          by_reference: false
                          multiple: true
            new:
                title: easyAdmin.group.title.new
            edit:
                title: easyAdmin.group.title.edit
            show:
                title: easyAdmin.group.name.mp
                fields:
                    - { property: 'id', label: 'ID' }
                    - { property: 'name', label: 'easyAdmin.groups.name' }
                    -
                      property: 'color'
                      label: 'trait.color'
                      template: '@ForsetiAdmin/easy_admin/field_color.html.twig'
                    -
                      property: 'roles'
                      label: 'easyAdmin.users.roles'
                      template: '@ForsetiAdmin/easy_admin/field_roles.html.twig'

            list:
                title: easyAdmin.group.name.mm
                fields:
                    - { property: 'id', label: 'ID' }
                    - { property: 'name', label: 'easyAdmin.groups.name' }
                    -
                      property: 'color'
                      label: 'trait.color'
                      template: '@ForsetiAdmin/easy_admin/field_color.html.twig'
                    -
                      property: 'roles'
                      label: 'easyAdmin.users.roles'
                      template: '@ForsetiAdmin/easy_admin/field_roles.html.twig'

