easy_admin:
    entities:
        User:
            class: Forseti\AdminBundle\Entity\User
            label: easyAdmin.user.name.mp
            initialPassword: password
            form:
                fields:
                    - { property: 'username', label: 'easyAdmin.users.username', type: text }
                    - { property: 'email', label: 'easyAdmin.users.email', type: email }
                    - 
                      property: 'groups'
                      label: 'easyAdmin.group.name.mm'
                      type: entity
                      type_options: 
                          expanded: false
                          multiple: true
                          class: Forseti\AdminBundle\Entity\Group
                    - { property: 'locked', label: 'easyAdmin.users.locked', type: 'checkbox' }
            new:
                title: easyAdmin.user.title.new
            edit:
                title: easyAdmin.user.title.edit   
            show:
                title: easyAdmin.user.name.mp
                fields:
                    - { property: 'username', label: 'easyAdmin.users.username' }
                    - { property: 'email', label: 'easyAdmin.users.email' }
                    - 
                      property: 'groups'
                      label: 'easyAdmin.group.name.mm' 
                      template: '@ForsetiAdmin/easy_admin/field_label.html.twig'
                    - { property: 'locked', label: 'easyAdmin.users.locked' }
                    - { property: 'expires_at', label: 'easyAdmin.users.expires_at' }
            list:
                title: easyAdmin.user.name.mm
                fields:
                    - { property: 'username', label: 'easyAdmin.users.username' }
                    - { property: 'email', label: 'easyAdmin.users.email', type: email }
                    - 
                      property: 'groups'
                      label: 'easyAdmin.group.name.mm' 
                      template: '@ForsetiAdmin/easy_admin/field_label.html.twig'
                    - { property: 'locked', label: 'easyAdmin.users.locked', type: toggle }

        Group:
            class: Forseti\AdminBundle\Entity\Group
            label: easyAdmin.group.name.mp
            form:
                fields:
                    - { property: 'name', label: 'easyAdmin.groups.name', type: text }
                    - 
                      property: 'roles' 
                      label: 'easyAdmin.groups.roles' 
                      type: choice
                      type_options: 
                          expanded: true
                          multiple: true
                          choices: "%roles.labels%"
                    - 
                      property: 'style'
                      label: 'easyAdmin.groups.style'
                      type: choice
                      type_options: 
                          choices: 
                              app.label.nolabel: nolabel
                              app.label.red: danger
                              app.label.yellow: warning 
                              app.label.info: info 
                              app.label.green: success 
                              app.label.blue: primary
                              app.label.hope: default
            new:
                title: easyAdmin.group.title.new
            edit:
                title: easyAdmin.group.title.edit  
            show:
                title: easyAdmin.group.name.mp
                fields: 
                    - { property: 'id', label: 'ID' }
                    - { property: 'name', label: 'easyAdmin.groups.name' }
                    - 
                      property: 'roles' 
                      label: 'easyAdmin.users.roles' 
                      template: '@ForsetiAdmin/easy_admin/field_roles.html.twig'
                      styles: "%roles.def%"
                    - 
                      property: 'style'
                      label: 'easyAdmin.groups.style' 
                      template: '@ForsetiAdmin/easy_admin/field_label.html.twig'
                      styles: 
                          nolabel: { label: 'app.label.nolabel' } 
                          danger: { label: 'app.label.red', class: 'danger' } 
                          warning: { label: 'app.label.yellow', class: 'warning' }  
                          info: { label: 'app.label.info', class: 'info' } 
                          success: { label: 'app.label.green', class: 'success' }  
                          primary: { label: 'app.label.blue', class: 'primary' } 
                          default: { label: 'app.label.hope', class: 'default' } 
            list:
                title: easyAdmin.group.name.mm
                fields: 
                    - { property: 'id', label: 'ID' }
                    - { property: 'name', label: 'easyAdmin.groups.name' }
                    - 
                      property: 'roles' 
                      label: 'easyAdmin.users.roles' 
                      template: '@ForsetiAdmin/easy_admin/field_roles.html.twig'
                      styles: "%roles.def%"
                    - 
                      property: 'style'
                      label: 'easyAdmin.groups.style' 
                      template: '@ForsetiAdmin/easy_admin/field_label.html.twig'
                      styles: 
                          nolabel: { label: 'app.label.nolabel' } 
                          danger: { label: 'app.label.red', class: 'danger' } 
                          warning: { label: 'app.label.yellow', class: 'warning' }  
                          info: { label: 'app.label.info', class: 'info' } 
                          success: { label: 'app.label.green', class: 'success' }  
                          primary: { label: 'app.label.blue', class: 'primary' } 
                          default: { label: 'app.label.hope', class: 'default' } 

    