security:
    role_hierarchy: &srh
        ROLE_USER_SHOW: ~
        ROLE_USER_LIST: ROLE_USER_SEARCH
        ROLE_USER_NEW: ~
        ROLE_USER_EDIT_OWN: ~
        ROLE_USER_EDIT: ROLE_USER_EDIT_OWN
        ROLE_USER_SOFTDELETE_OWN: ~
        ROLE_USER_SOFTDELETE: ROLE_USER_SOFTDELETE_OWN
        ROLE_USER_DELETE: ~
        ROLE_USER_FLAG: ~
        ROLE_USER_ALL:
            - ROLE_USER_SHOW
            - ROLE_USER_LIST
            - ROLE_USER_NEW
            - ROLE_USER_EDIT
            - ROLE_USER_DELETE
            - ROLE_USER_SOFTDELETE
            - ROLE_USER_FLAG

easy_admin:
    entities:
        User:
            class: Forseti\AdminBundle\Entity\User
            controller: Forseti\AdminBundle\Controller\UserAdminController
            label: easyAdmin.user.name.mp
            initialPassword: password
            form:
                fields:
                    - { property: 'username', label: 'easyAdmin.users.username', type: text }
                    - { property: 'email', label: 'easyAdmin.users.email', type: email }
                    - 
                      property: 'groups'
                      label: 'easyAdmin.group.name.mm'
                      type: entity
                      type_options: 
                          expanded: false
                          multiple: true
                          class: Forseti\AdminBundle\Entity\Group
                    - { property: 'locked', label: 'easyAdmin.users.locked', type: 'checkbox' }
            new:
                title: easyAdmin.user.title.new
            edit:
                title: easyAdmin.user.title.edit   
            show:
                title: easyAdmin.user.name.mp
                fields:
                    - { property: 'username', label: 'easyAdmin.users.username' }
                    - { property: 'email', label: 'easyAdmin.users.email' }
                    - 
                      property: 'groups'
                      label: 'easyAdmin.group.name.mm' 
                      template: '@ForsetiAdmin/easy_admin/field_label.html.twig'
                    - { property: 'locked', label: 'easyAdmin.users.locked' }
                    - { property: 'expires_at', label: 'easyAdmin.users.expires_at' }
            list:
                title: easyAdmin.user.name.mm
                fields:
                    - { property: 'username', label: 'easyAdmin.users.username' }
                    - { property: 'email', label: 'easyAdmin.users.email', type: email }
                    - 
                      property: 'groups'
                      label: 'easyAdmin.group.name.mm' 
                      template: '@ForsetiAdmin/easy_admin/field_label.html.twig'
                    - { property: 'locked', label: 'easyAdmin.users.locked', type: toggle }

